[package]
name = "rust"
version = "0.1.0"
authors = ["glumes <zhaoying9402@gmail.com>"]
edition = "2018"

[dependencies]
jni = { version = "0.10.2" , default-features = false}
android_logger = { version = "0.5.3"}

[profile.release]
lto = true

[lib]
name = "rust"
crate-type = ["cdylib"]